spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartwalletapp
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: admin
  server:
    address: 0.0.0.0
jwt:
  signerKey: "1g588fp61K3ru1mWsoT900vsoqykoJs63qAzM2917QKkIAf1ff0WwGHvNu3+vmJ7"


Way4Url:
  ApiKey: "http://10.145.48.222:17000/webservice_int/ws"

# logging:
#   level:
#     org.springframework.oxm: DEBUG
#     com.sun.xml.bind: DEBUG
#     com.sun.xml.internal.bind: DEBUG
#     org.apache.cxf.interceptor: DEBUG
#     org.springframework.ws.client.MessageTracing:
#       sent: TRACE
#       received: TRACE